server:
  port: 8080
  servlet:
    context-path: /crud

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/DinhPhongShoeStore"
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "lOMFgbTC3yBK/9TmcrFH4lFT50GNK0qt8VZ2ZCip1ih/mCNiCEOnTrGFs0tB1vHX\n"